;METADATA=(Diff=true, UseCommands=true)
[/Script/LevelSwitcher.LevelSwitcherSettings]
+FavoriteLevels=/Game/Letgo/Map/EliotMap2
+FavoriteLevels=/Game/Letgo/Map/MapFinal_WP
StartupLevel=/Game/Letgo/Map/EliotMap2

